[package]
name = "lolog"
version = "0.1.2"
authors = ["Henry Precheur <henry@precheur.org>"]
description = "Logging library"
repository = "https://github.com/henryprecheur/lolog/"
license = "ISC"

[dependencies]
log = "^0.3"
time = "^0.1"
